<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_Use your Google accountUse your Google_c9bfe0</name>
   <tag></tag>
   <elementGuidId>3218d229-8798-433f-9501-72252f65d46e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#u_0_1_Uo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='u_0_1_Uo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>form</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>e0fd48fe-ba26-4a9c-b30d-0d3b4efd77d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>2b74840f-8eb4-40f8-a2f6-eff51f75d7af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>method</name>
      <type>Main</type>
      <value>post</value>
      <webElementGuid>ecb3dc81-a571-4472-928d-bfaf9e80b2f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>action</name>
      <type>Main</type>
      <value>/ajax/recover/initiate/?recover_method=recover_openid&amp;selected_cuid=AYh4aReeGVEDoXXko4ff5N4Qc8gLwoEbm7oOs0dB6UmWysSXJd-rAc2_IUiD0neYAvYeGBaRbwooz9levhcL-U_4KEt-BVDq48nhEcPePI_vM5hIM5-wKx4qN8kqHe2B9vsNx6QdIyBefbXA9ANW3XP7Yrc-pPcpq_GdP1X-YauhR0aoqNG_PKa9_bGCnaIEESxs6pE_yA_4tO05aASwjLkexIueLmymOPLtDx0PeER21eJ1x6uAzuUPOKLWKgWCOsBCrxidBZl5Dyn--cnyDUfxmdV4_VF4UbpAaV1PxPvfKA&amp;lara=1</value>
      <webElementGuid>9f9bf543-886e-443f-991e-aeebc9dee84d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>u_0_1_Uo</value>
      <webElementGuid>ebd29342-b82e-47d4-92fe-a47c348ced6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Use your Google accountUse your Google accountThe password you've entered is incorrect.Quickly log in with your Google account.vegetarianalami@gmail.comLenon SmithFacebook userNot you?Try another wayContinueLog in with password</value>
      <webElementGuid>e3a7df76-a1a9-4417-a623-c06e99302a82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_0_1_Uo&quot;)</value>
      <webElementGuid>6aac66ef-de1d-4790-8bf0-e2049e08e79e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//form[@id='u_0_1_Uo']</value>
      <webElementGuid>e3a01ef8-89ea-4333-8ad1-bedd5a1bf89c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lara_strong_rec_screen']/div/form</value>
      <webElementGuid>e864a752-ae4b-4a77-9b2e-82cbdaec7aeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>1111a00c-727f-4f57-89db-8a13b82db1eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[@id = 'u_0_1_Uo' and (text() = concat(&quot;Use your Google accountUse your Google accountThe password you&quot; , &quot;'&quot; , &quot;ve entered is incorrect.Quickly log in with your Google account.vegetarianalami@gmail.comLenon SmithFacebook userNot you?Try another wayContinueLog in with password&quot;) or . = concat(&quot;Use your Google accountUse your Google accountThe password you&quot; , &quot;'&quot; , &quot;ve entered is incorrect.Quickly log in with your Google account.vegetarianalami@gmail.comLenon SmithFacebook userNot you?Try another wayContinueLog in with password&quot;))]</value>
      <webElementGuid>7dd1b4ea-65d5-4f82-a993-a034fef58e13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
